name: icon-automation
on:
  push:
    branches:
      - master
    # file paths to consider in the event. Optional; defaults to all.
    paths:
      - package.json

jobs:
  icon_automation:
    name: figma icon automation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          node-version: '20.x'
      - run: npm install -g pnpm
      - run: pnpm install
      - run: pnpm fetch:svg
        env:
          FIGMA_FILE_URL: ${{ secrets.FIGMA_FILE_URL }}
          FIGMA_TOKEN: ${{ secrets.FIGMA_TOKEN }}
      - run: pnpm generate
      - run: pnpm build:bundle
      - run: echo "//verdaccio.teiron-inc.cn:4873/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > ~/.npmrc
      - run: pnpm publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - run: pnpm build
      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v1.2.5
        with:
          build_dir: docs
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
